### ISSUE TITLE
Don't allow login with empty password

### ISSUE THREAD

**Issue by nando-digital** [apognu/tuigreet#100]
Tuigreet tries to login before a password could be typed in. That means that you need at least 2 tries to log in which results in less attempts to actually type in a successful password. This is not ideal because on many systems your account gets locked for 10 minutes after 3 failed logins.
To reproduce you can open tuigreet, type in your username, press enter (or tab) and then escape and that multiple times. Then you see that you never typed in your password but your account is locked due to 3 failed login attempts.
I think [this](https://github.com/apognu/tuigreet/blob/0.8.0/src/keyboard.rs#L136-L151) is the code that would have to be changed to also check if the password is not empty and only then tries to login. So this is easy to fix if there's a function similar to `greeter.username.is_empty()` just for the password.

**Comment by apognu** [comment]
Is your issue that `tuigreet` tries to authenticate when you press Enter or Tab with an empty password field?

If so, this behavior will not be changed as it is a valid case for an authentication workflow (as an example, an empty password could trigger a fingerprint or security key scan). This is in the scope of the PAM configuration.

**Comment by apognu** [comment]
Will close this as I believe it to be a supported use case. Please respond if you wish to discuss.
