### ISSUE TITLE
How to achieve the same look as the one in the README?

### ISSUE THREAD

**Issue by pashafst** [apognu/tuigreet#101]
Hi,

I want to make my tuigreet more beautiful, so i'm trying to edit my linux console's configs. The image in README looks sharp, so I want to make it look like that. Right now I'm trying to use kmscon to replace the linux console, so that ttf fonts can be used. Following the guide in the [wiki](https://wiki.archlinux.org/title/KMSCON), I disabled the tty1 service and replaced it with kmscon tty1 service, and now I'm launching kmscon on boot. The problem is, tuigreet is not shown on kmscon, instead it shows the normal login service. 

How can I solve this? And is there a simpler solution to achieve the same look as README image?

**Comment by apognu** [comment]
Unfortunately, I will not be able to help in that regard, I do not use `kmscon`. The screenshot in the README was taken from a terminal emulator; my actual instance I use for login runs in a regular `tty`.
