### ISSUE TITLE
black screen instead of tuigreet

### ISSUE THREAD

**Issue by UniversalWill** [apognu/tuigreet#102]
I wanted to switch to systemd hook following [Using_systemd_instead_of_busybox_on_early_init](https://wiki.archlinux.org/title/Improving_performance/Boot_process#Using_systemd_instead_of_busybox_on_early_init) but I got the error "Failed to start Virtual Console Setup" trying to fix it I stopped displaying tuigreeter. After booting it just blinks the cursor on a black screen, changing vt doesn't help. Going back to base and udev hooks and reinstalling greetd and tuigreet doesn't help either.  
Distro: Arch Linux
Kernel: 6.4.12-zen

**Comment by apognu** [comment]
Do other `greetd` greeters work? That error message does not seem related to `greetd` or `tuigreet`.

**Comment by apognu** [comment]
Closing until more information comes up.
