### ISSUE TITLE
cpu usage is tenfold after commit fd86e67 Limit UI refresh frame rate

### ISSUE THREAD

**Issue by artist-linux** [apognu/tuigreet#113]
The cpu usage is tenfold after commit fd86e67 Limit UI refresh frame rate.
Before this commit the cpu usage for an idle tuigreet process was at about 0.65 percent.
After this commit the cpu usage for an idle tuigreet process is at about 6.5 percent.
I'm not sure if this is related, but the cursor in the password field blinks at very irregular intervals.

**Comment by artist-linux** [comment]
Thank you for looking into this.
The cursor is about the same as before, so that is not related to this issue.
I did find this crossterm issue: https://github.com/apognu/tuigreet/issues/71. Would using SetCursorStyle to disable blinking help? This was introduced in https://github.com/crossterm-rs/crossterm/pull/742/commits
In case I can help testing please let me know.

**Comment by apognu** [comment]
The latest commit on `master` should hopefully revert the CPU usage regression (and maybe even improve it a bit). Could you verify that things are working properly and that you are not seeing the issue anymore?

**Comment by artist-linux** [comment]
Thank you very much for the update :-)
The CPU usage is now at about 0.3 percent, so indeed even quite lower than originally. And the result, as in blinking, is a lot better.
The attempts to disable blinking probably failed because this requires root privillege, or at least write acces to perform:
echo 0 > /sys/class/graphics/fbcon/cursor_blink
I'll try to find the correct kernel parameter for users who want to use that tomorrow, so this might be added to the README.md.
