### ISSUE TITLE
Possibly a bug or misconfiguration: startup log interferes with the tui

### ISSUE THREAD

**Issue by Floataqq** [apognu/tuigreet#117]
When i start my pc the tui appears before the startup log finishes, so the log messages for NetworkManager and docker appear right where the input fields are. When i type the text overwrites the log messages. 

it just appeared for no reason, i did not do anything related to them apart from a few system upgrades and installing docker. Unlike the other issue, all the service startups succeed.

**Comment by apognu** [comment]
Hey, this is probably a duplicate of #68. I am still unsure if I can fix it on my end.

**Comment by Floataqq** [comment]
sorry for the duplicate

for anyone that will read this issue, i managed to fix it by using plymouth with no theme
