### ISSUE TITLE
Greetings with ü seem to not show up

### ISSUE THREAD

**Issue by MTRNord** [apognu/tuigreet#12]
Hi I have this command:

![image](https://user-images.githubusercontent.com/1374914/103221572-47125980-4923-11eb-92bb-5ae720e5f48e.png)

But the greeting never gets shown. Is it the ü or is it the escaped quotes?

**Comment by Nox-404** [comment]
The `-i` loads the `/etc/issue` file, it doesn't take any arguments.

**Comment by Nox-404** [comment]
Oh and I tried with a `ü` and it worked fine

**Comment by MTRNord** [comment]
Ohh ok :D that probably explains it. I will try that :) Thanks!

**Comment by Nox-404** [comment]
@MTRNord did it work ?

**Comment by MTRNord** [comment]
Sorry that it took me so long to reply :) It works fine now :D Thanks for the help!
