### ISSUE TITLE
Change keyboard layout?

### ISSUE THREAD

**Issue by ConiKost** [apognu/tuigreet#121]
Is there any way to change the default keyboard layout, when using tuigreet? It seems to use us keyboard layout, while I would like to use a different keyboard layout, since I have otherwise trouble to enter my password.

**Comment by apognu** [comment]
There is no keyboard layout management in tuigreet itself. It is a terminal UI that should use your Linux virtual console configuration, with respect to fonts and keyboard layouts.

**Comment by ConiKost** [comment]
What do you mean by virtual console? The "classic" tty, which I can switch from X11 via Ctrl+Alt+F[1-6]? If so, that's already running the correct keyboard layout I need. I have there 'de' (German) keyboard layout configured, but it seems, that tuigreet ignories this and uses 'us' only.

**Comment by ConiKost** [comment]
Just an addition: Someone asked the same for the gtkgreeter. The author of greetd/gtkgreeter replied, that this is being handle by the underlying `sway` or `cage`.

**Comment by apognu** [comment]
That's the thing, tuigreet doesn't run in sway, or cage or X11, it runs directly on a Linux TTY, so I am having trouble understanding where the issue could come from.

I'll have a try when I come back from holiday, but last I tried, tuigreet had no say in the matter (maybe the way it is started forces a locale/keyboard layout?).

**Comment by ConiKost** [comment]
> That's the thing, tuigreet doesn't run in sway, or cage or X11, it runs directly on a Linux TTY, so I am having trouble understanding where the issue could come from.

Thanks for clarifying. I wasn't sure about that, how does tuigreet run.

> I'll have a try when I come back from holiday, but last I tried, tuigreet had no say in the matter (maybe the way it is started forces a locale/keyboard layout?).

Enjoy your holiday!

**Comment by ConiKost** [comment]
m( Sorry, closing here. Found the cause. There was indeed a wrong keymap, when spawning the process. Sorry for the noise. All fine here.
