### ISSUE TITLE
Feature request: Allow multiple asterisks-chars

### ISSUE THREAD

**Issue by Kaligule** [apognu/tuigreet#122]
Currently you can use `--asterisks-char x` to select a _single_ "character to be used to redact secrets (default: *)".

I suggest allowing to use _multiple_ characters here: `--asterisks-char xyz`. Then when the user types in his password, for each letter a random character from the list would be shown.

## why?

This would allow the user to look cool when typing his password, because it looks like their password is `ᐷᐐᐖᐚᐬᐰᐹ`

## is this feature creep?

Yes, sorry.
I still think it would be cool, though.

**Comment by Kaligule** [comment]
That looks so cool :) I won't be able to test main for a few weeks, but I looked at the code and it looks right. Well done and thank you.

**Comment by apognu** [comment]
Thanks! I'll close this until then, feel free to reopen if you notice something wrong. :)
