### ISSUE TITLE
--remember* options is not working. /var/cache/tuigreet is empty

### ISSUE THREAD

**Issue by SDD701** [apognu/tuigreet#123]
Hello. Looks like tuigreet does not create any files is /var/cache/tuigreet even if I set some --remember* options (so it doesn't remember anything).

OS: Gentoo 

Greetd config:
```
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 7

# The default session, also known as the greeter.
[default_session]

# `agreety` is the bundled agetty/login-lookalike. You can replace `$SHELL`
# with whatever you want started, such as `sway`.
command = "tuigreet --width 100 --time --remember --remember-session --asterisks --asterisks-char X --power-shutdown 'doas poweroff' --power-reboot 'doas reboot'"

# The user to run the command as. The privileges this user must have depends
# on the greeter. A graphical greeter may for example require the user to be
# in the `video` group.
user = "SDD"
```

**Comment by apognu** [comment]
What are the permissions for `/var/cache/tuigreet`? It should be readable and writable by the user `greetd` runs as (in your case, as I can see, your own user?).

**Comment by apognu** [comment]
Usually, at least how it's recommended by greetd, it (and therefore its greeters) should run as the `greetd` user and not your own (security-wise, it does defeat the purpose of authentication if the thing that authenticates you already runs as you).

So it is expected that packagers set `/var/cache/tuigreet` as owned by greetd.

You could add your user in that group, but I would kindly recommend that you run `greetd` as its own user instead.

**Comment by SDD701** [comment]
> Usually, at least how it's recommended by greetd, it (and therefore its greeters) should run as the `greetd` user and not your own (security-wise, it does defeat the purpose of authentication if the thing that authenticates you already runs as you).
> 
> So it is expected that packagers set `/var/cache/tuigreet` as owned by greetd.
> 
> You could add your user in that group, but I would kindly recommend that you run `greetd` as its own user instead. Basically, change to `user = "greetd"` in the configuration.

Changing user to greetd fixed the issue. Thank you

**Comment by Kalthun** [comment]
In case someone else is looking at this post. I had a similar issue but for me the fix was setting `user = "greeter"`.

![Image](https://github.com/user-attachments/assets/77163ed2-7724-4337-812c-63a98d115f62)
