### ISSUE TITLE
Backlight hotkeys produce typed characters

### ISSUE THREAD

**Issue by LRitzdorf** [apognu/tuigreet#128]
On my (Arch) system, pressing a backlight hotkey causes a character to be typed into the active tuigreet text field. This character renders as a blank space when entered into a field where it's actually visible (i.e. not the password field). I don't observe this effect when using a TTY normally (i.e. when logged into a shell), so I'm guessing this is somehow related to tuigreet in particular?

For reference, my backlight hotkeys are set up [via acpid](https://wiki.archlinux.org/title/Acpid#Enabling_backlight_control), so that they function even when not in a graphical environment. I'm not sure whether/how this might affect keypresses being eaten or passed down to TTY processes, unfortunately, but would be willing to test any settings that might be relevant!

**Comment by LRitzdorf** [comment]
...okay, after a quick test, the ACPI settings have no effect. The character is typed both with and without acpid's handling of backlight events.

**Comment by apognu** [comment]
What version of `tuigreet` are you using?

**Comment by LRitzdorf** [comment]
Hm — 0.7.3 according to `tuigreet -v`, but the Arch package is currently numbered 0.8.0. That's interesting...

**Comment by apognu** [comment]
Yes this was an issue on my part with numbering from within the app, you are running 0.8.0.

I do believe that the issue you mention was fixed since, but was not yet released as a stable package, but I would like to make sure. Are you able/willing to build/install the binary from the HEAD of the repo to confirm? If you still have the issue there, I would like to be able to reproduce it.

**Comment by LRitzdorf** [comment]
Sure! I'm guessing I can just build AUR's `greetd-tuigreet-git`? If so, I'll try that later today.

**Comment by LRitzdorf** [comment]
Yep, confirmed that the current Git build fixes this issue. Thanks for the tip!
