### ISSUE TITLE
tuigreet doesn't show prompt text to fingerprint for fprint with '--user-menu' flag

### ISSUE THREAD

**Issue by lootboxer** [apognu/tuigreet#131]
Hi! When I use --user-menu flag, fprint prompt doesn't appear after select of user.

**Comment by apognu** [comment]
Hi, could you provide the information listed in the Bug Report issue template, please? Also, for your specific issue, maybe an excerpt of your PAM configuration could help me reproduce.

Thank you.

**Comment by lootboxer** [comment]
> Hi, could you provide the information listed in the Bug Report issue template, please? Also, for your specific issue, maybe an excerpt of your PAM configuration could help me reproduce.
> 
> Thank you.

Oh. I'm sorry, no problem :)

**Comment by apognu** [comment]
You did not have to close this, you could have added the information as a comment :)

**Comment by lootboxer** [comment]
I thought you meant to recreate it as a bug =D.

I just realized that this is not login not working, tuigreet doesn't show login screen with the text request to enter fingerprint. This is wait for entering fingerprint silently.  

**Describe the bug**
Tuigreet doesn't show text with request to enter fingerprint, when I login with --user-menu flag. 

**To Reproduce**
Steps to reproduce the behavior:
1. To add --user-menu flag in command of starting session.
2. To try login by select user in user menu.
3. To try use fingerprint to login.

**Expected behavior**

Tuigreet shows window with request to enter fingerprint.

**System information:**
 - Distribution:Linux void 6.6.27
 - `greetd` version: 0.10.0_1
 - `tuigreet` version: 0.8.0_3
 - Installation method (from source, package, binary, etc.): package by xbps
 - `tuigreet` command line: `tuigreet --power-no-setsid --power-shutdown 'loginctl poweroff' --power-reboo
t 'loginctl reboot' --user-menu --cmd '/usr/local/bin/sway-session'`

**Comment by apognu** [comment]
Ok, thank you! I was going to tell you it is most likely a big in the UI rather than an issue with authentication. Good news is you already realized that and that I have a fix almost ready to be pushed.

Thanks for providing details!

**Comment by apognu** [comment]
This should now be fixed on the head of the main branch!
