### ISSUE TITLE
Allow specifing session type for --cmd session

### ISSUE THREAD

**Issue by tmccombs** [apognu/tuigreet#148]
When tuigreet uses a session from one of the session directories it can infer the session type from the folder, but if the default session from the cms option is used, then XDG_SESSION_TYPE isn't set. I would like a way to specify the value of the session type (wayland or x11) when using the cms session.

Alternatively, have a way to set environment variables that are set _before_ the pam session is started when using the cmd session.

**Comment by apognu** [comment]
@tmccombs Do you have any opinion on this?

**Comment by apognu** [comment]
This has been merged onto the main branch and will be included in 0.10.0. If you're using a bleeding-edge version of `tuigreet`, feel free to test it out and create new issues if you notice problems.
