### ISSUE TITLE
No session mode (that launches console)

### ISSUE THREAD

**Issue by lalishansh** [apognu/tuigreet#149]
Hi Everyone,

I'm currently using nixos and am trying to work with multiple users in single environment (with different sessions).
What i want is launch console in server type configuration or whenever window manager fails to start.

Currently it just shows blank screen and reverts to tuigreet screen.

**Comment by apognu** [comment]
Hi! I'm sorry, I do not fully understand what you are trying to achieve here, can you elaborate?

**Comment by lalishansh** [comment]
like agreety, launch console mode

**Comment by apognu** [comment]
Do you mean launching a shell from `ruigreet`? You can change the command (F2) to `bash` (or whichever shell you use) and it will spawn it after authentication.

**Comment by lalishansh** [comment]
Yup that's what I was looking for, Thankx

**Comment by acuteaangle** [comment]
Note: you can use `$SHELL` as the command to use the user’s default shell.
As the default: `--cmd '$SHELL'` (with single quotes)
