### ISSUE TITLE
X sessions broken

### ISSUE THREAD

**Issue by nabijaczleweli** [apognu/tuigreet#15]
`/usr/share/wayland-sessions/*.desktop`s specify `Exec=` to the display server, and work stand-alone.

`/usr/share/xsessions/*.desktop`s specify `Exec=` to the WM, and therefore need some form of X server configuration to be performed *before* they're started.

**Comment by xukai92** [comment]
Any idea how to fix this?

**Comment by nabijaczleweli** [comment]
Perform actual X session initialisation – starting an X server is a good start.

**Comment by xukai92** [comment]
Yeah I did do startx to solve the issue. But how to make tuigreet deal with X and Waylan differently?

**Comment by GamerPanda99** [comment]
Well tuigreet just takes an arbitrary command right? sou you can simply build a script to do your init and run that script?

**Comment by xukai92** [comment]
> Well tuigreet just takes an arbitrary command right? sou you can simply build a script to do your init and run that script?

Yes I'm doing this ATM.

The annoying thing is that those X sessions that doesn't work would still be listed by tuigreet. 
I really want to make everything listed work fine.

Could I make tuigreet somehow handle X sessions and wayland sessions differently?

**Comment by apognu** [comment]
I'll get on this as soon as I am able to install some X WM to reproduce this.

`greetd` can only run one command after authentication succeeds, so this behavior cannot be changed. However, maybe I could allow customizing the directory where `desktop` files are looked up at, so you may provide your own, curated and customized.

Would this solve your issue or did I misunderstand?

**Comment by xukai92** [comment]
Destop files seem to be located in the same directly, no?
I don't know the solution but it seems that maybe provide a way to manually configure each sesseion is fine?

**Comment by apognu** [comment]
Two directories are used to look for `desktop` files: `/usr/share/xsessions` and `/usr/share/wayland-sessions`. Those are the default directories where the various window managers drop their session configs.

I'll look at adding an option to change those directories so you can customize which sessions are displayed and what is executed.

**Comment by apognu** [comment]
You can now pass a new `--sessions` argument to `tuigreet`, as a colon-separated list of directories where it will try and load `desktop` files for your sessions, so you can fine-tune the list.

It is now available on `master` and will be included in the next version.

**Comment by paulolieuthier** [comment]
@apognu it would still be nice if tuigreet could correctly instruct greetd to initialize X11 for default sessions in /usr/share/xsessions. [QtGreet does that](https://gitlab.com/marcusbritanicus/QtGreet/-/blob/main/src/backends/greetd/GreetdManager.cpp#L102) and that's what [greet expects](https://lists.sr.ht/~kennylevinsen/greetd-devel/%3CCACtzxuBbUqSSypHR2sO81ZXCwFeODT8STo%3Dt-uCpWfdgcer68g%40mail.gmail.com%3E).

Are you willing to merge a PR for that?

**Comment by apognu** [comment]
In principle, the more plug-and-play everything is, the better.

We need to make sure we do not make any wrong assumptions about what this means (for example, I don't have `xinit` on my own system). I've made this mistake in the past and it came to bite me in the ass later.

But yes, a PR for this would be appreciated. Testing it is going to be tough, but I think it could be a nice addition.
