### ISSUE TITLE
/etc/issue coloring not showing

### ISSUE THREAD

**Issue by TeakKey7** [apognu/tuigreet#150]
**Describe the bug**
When using _issue_ in tuigreet, ANSI color coding is not supported

**Expected behavior**
When using ANSI in /etc/issue, you can normally see the color of your greeting when logging into a TTY

**System information:**
 - Distribution: Arch
 - `greetd` version: 0.10.3-1
 - `tuigreet` version: 0.9.1-1
 - Installation method (from source, package, binary, etc.): Pacman
 - `tuigreet` command line: tuigreet --asterisks-char • -r --issue --remember-user-session -t --sessions /etc/greetd/sessions

**Additional context**
/etc/issue: 
```\e[H\e[2J
                                                             \e[1;30m| \e[34m\r \s
      \e[36;1m/\\\\                        \e[37m||      \e[36m| =                 \e[30m|
     \e[36m/  \\\\                       \e[37m||      \e[36m|                   \e[30m| \e[32m\t
    \e[1;36m/ \e[0;36m.. \e[1m\\\\   \e[37m//==\\\\\\ ||/= /==\\\\ ||/=\\\\  \e[36m| | |/\\\\ |  | \\\\ /  \e[30m| \e[32m\d
   \e[0;36m/ .  . \\\\ \e[37m||    || ||  ||     ||  ||  \e[36m| | |  | |  |   X   \e[1;30m|
  \e[0;36m/  .  .  \\\\ \e[37m\\\\\\==/| ||   \\\\==/ ||  ||  \e[36m| | |  |\  \\/|  / \\\\ \e[1;30m| \e[31m\U
 \e[0;36m/ ..    .. \\\\   \e[0;37mA simple, lightweight linux distribution.   \e[1;30m|
\e[0;36m/_'        `_\\\\                                              \e[1;30m| \e[35m\l \e[0mon \e[1;33m\n
\e[0m
```

**Debug log**
Run `tuigreet` with the `-d [FILE]` option to log tracing information into the
specified file, to append here.
**I could not get tuigreet to give a deubg file after restarting the greetd service multiple times with -d in the config file's command**

![fbgrab](https://github.com/user-attachments/assets/dda6c42d-2c1f-4065-99b3-f25b3ecd8fcb)

**Comment by apognu** [comment]
@TeakKey7, I started implementing this in #151, could you have a go at the binary in [this action](https://github.com/apognu/tuigreet/actions/runs/10291782044) and tell me if it works properly for your use case?

I have some more testing to do on my side, but your feedback would go a long way.

Thank you.

**Comment by TeakKey7** [comment]
![greeter](https://github.com/user-attachments/assets/f4b517fc-1e8b-420a-b023-5567fe2d366f)
![tty](https://github.com/user-attachments/assets/6f104731-60fe-4e39-9811-b666bdb53ba7)
I appreciate the assistance. Here is what I get.

**Comment by apognu** [comment]
Can you try running `tuigreet` with the following option: `--greet-align left`? I believe the weird offsets we see are because it is centered by default.

**Comment by apognu** [comment]
There is still something wrong with the display, even when aligned left. Good news is I think I know how to fix that. There will also most probably be a width issue, where broad issue content will be too long to be displayed in the container.

**Comment by apognu** [comment]
I am at a state where things look _quite_ good (not perfect, though):

 * There is one extra space on the last line spelling our Arch Linux ;
 * "\U" is not supported to be replaced by the number of logged-in users ;
 * The "bold" statement of the yellow coloring of the hostname and that of the vertical bar is not applied (I believe this is a limitation of the crate I use, I need to check) ;

![tuigreet-ansi](https://github.com/user-attachments/assets/15afd4af-a901-4e8b-bfc3-08905ca8ca06)

**Comment by apognu** [comment]
Hey, can you try out the build from [this action](https://github.com/apognu/tuigreet/actions/runs/10348781152)? I think it is looking quite okay.

Thanks.

**Comment by TeakKey7** [comment]
![secondtry](https://github.com/user-attachments/assets/0bf1e845-062b-401f-9a21-ec8bfff13c94)
I was able to replicate your view! \U is also working. I apologize for going unresponsive over the weekend. Thanks for your help! I will keep an eye on it if you have any other tests for me. :)

**Comment by TeakKey7** [comment]
I am curious, how are you getting a seemingly emulated console on yours? Your font looks very pretty compared to default Linux console. I am torn on raw hardware look vs pretty and polished

**Comment by apognu** [comment]
No problem, we all need our weekends.

Yeah I also took the opportunity to implement some of the missing escape sequences. Glad to know it looks good.

For your other question, I am afraid there is no magic, the screenshot comes from `tuigreet` running from a terminal emulator in my user session, not from a Linux console. I also wish it looked like that. 😅

**Comment by apognu** [comment]
This is merged on the main branch and will be included in the next tagged release.

**Comment by LittFlower** [comment]
I apologize for reopening this thread... But I'm still experiencing the problem (I've added `--width 90 --greet-align left`), and I'm still not able to draw this graphic correctly at my tuigreet, but I'm already able to see it correctly in tty, which suggests that my /etc/issue settings should be fine.

我的配置命令如下：

```
command = "tuigreet --asterisks --issue -t --remember --width 90 --greet-align left --theme 'border=magenta;text=cyan;prompt=green;time=red;button=lavender;container=black;input=red'"
```

**Comment by apognu** [comment]
Which version of `tuigreet` are you running? This change has not been released in a tagged version yet, so is only available when compiling from the main branch.

**Comment by LittFlower** [comment]
the version about greetd and tuigreet as follows:

 - `greetd` version: 0.10.3-1
 - `tuigreet` version: 0.9.1-1
 - Installation method: [pacman](https://archlinux.org/packages/extra/x86_64/greetd-tuigreet/)

**Comment by apognu** [comment]
You do not have the version where this is released, you either have to wait until the release or compile from source.
