### ISSUE TITLE
How to test my greetd/tuigreet config

### ISSUE THREAD

**Issue by teto** [apognu/tuigreet#160]
I want to test my config without logging out of my session since it is slow and cumbersome. I tried to start `greetd -s /path/to/sock` so that I can export GREETD_SOCK before starting tuigreet but no `/path/to/sock` gets created.

**Comment by teto** [comment]
I am running 0.9.1 and "Choose sessions" is empty even though I've configured tuigreet with a valid `--sessions /nix/store/.../share/wayland-sessions` folder that contains a `sway.desktop`. starting tuigreet `-d /tmp/tuigreet.log` doesn't create anyfile (it starts as the "greetd" user), do I need to export some variable before to toggle debugging ?.

**Comment by apognu** [comment]
I cannot really help as far as to how to run another `greetd` instance. However, for development, I use a small piece of software that I developed, [greetd-stub](https://github.com/apognu/greetd-stub), that simulates `greetd`'s RPC without actually creating session.

It might not be perfect and I will not provide support for it, but you can give it a try.

As for your sessions issue, it's a bit hard to determine. I've added some more debugging likes to the master version if you're willing to try. But yes, running `tuigreet -d` should be enough.

**Comment by teto** [comment]
it actually worked after a reboot. The greetd unit was updated but the service was not reloaded (probably because it kills your current session) so my changes were not accounted for, /tmp/tuigreet.log was created, my sway.desktop was seen by tuigreet and I managed to make it see my gnome desktop (my initial goal). Sry for noise.
