### ISSUE TITLE
Package is available on Gentoo

### ISSUE THREAD

**Issue by epsilon-0** [apognu/tuigreet#2]
I've added tuigreet as a package on Gentoo, available here:
https://packages.gentoo.org/packages/gui-apps/tuigreet

Thanks a lot for making this :smiley_cat: 

I'm wondering if there is going to be a release anytime soon?
I remember there was a `0.1.0` release but it seems to have been removed and replaced by the `tip` release, but that one is not suitable for packaging as it keeps changing (checksum and dependencies).

Thanks again!

**Comment by apognu** [comment]
Thanks for doing this!

Yes, the real first tagged version is coming, now that I am satisfied with the initial feature set. I hope I'll be able to publish it either this weekend or the next.

**Comment by apognu** [comment]
Would you be willing to make a pull request on the `README` to give instructions on how to install `tuigreet` on Gentoo? Never used the distro, wouldn't want to mess this up.

**Comment by epsilon-0** [comment]
done

**Comment by apognu** [comment]
For your information, [0.1.0](https://github.com/apognu/tuigreet/releases/0.1.0) is out.

**Comment by epsilon-0** [comment]
awesome :)
