### ISSUE TITLE
Ctrl+U for input reset

### ISSUE THREAD

**Issue by frcl** [apognu/tuigreet#20]
In most terminal programs Crtl+U can be used to clear the current input. This is very useful for password propts, where there is no visual feedback. So when I type the wrong password, then remember midway that I was thinking of the wrong password, I just press Ctrl+U and start again.

tuigreet does not seem to support that feature, at least it is not working for me. But it would be great if it did.

**Comment by apognu** [comment]
Great idea! And indeed, tuigreet does not support this currently. I'll look into it.

**Comment by apognu** [comment]
This should be implemented on `master` right now and will be included in the next release.

**Comment by frcl** [comment]
Thanks, seems to work perfectly.
