### ISSUE TITLE
tuigreet as a screen locker

### ISSUE THREAD

**Issue by rYR79435** [apognu/tuigreet#21]
Is it possible to use tuigreet as a screen locker?
I know this depends on greetd, but I couldn't figure out if it supports such functionality.

**Comment by apognu** [comment]
As far as I know, greetd does not support any kind of lockscreen functionality, and its architecture would not permit it anyway.

You may have more luck asking this on the greetd mailing list, but I'm quite sure what the answer is.

**Comment by rYR79435** [comment]
Thank you for clarifying.
