### ISSUE TITLE
[Feature request] Spacing between content and screen (like screenshot)

### ISSUE THREAD

**Issue by rYR79435** [apognu/tuigreet#22]
The first screenshot in the README looks like there would be space between the date and the top screen border. In reality there is none.
Is this a bug or a feature request?

**Comment by apognu** [comment]
The padding on the screen is applied by my terminal emulator, just for the purpose of this screenshot. As of now, there is no padding option for the whole screen, only the middle box.

**Comment by rYR79435** [comment]
Could you point me towards how I can run tuigreet from my terminal?
Simply running it (after cargo build) yields `Permission denied (os error 13)`. Running it as root then says `GREETD_SOCK` must be defined. Now the only thing I could think of putting in that env var was the path to my current terminal like so: `sudo env GREETD_SOCK=$(tty) ./target/debug/tuigreet`, but that just gives `Connection refused (os error 111)`.

In case it matters, I'm trying this in Alacritty and using the installed `tuigreet` vs. the freshly built one didn't matter.

**Comment by apognu** [comment]
`tuigreet` is not really supposed to be run in a terminal emulator, except for development purposes (so you don't have to log out to test your changes).

`GREETD_SOCK` should point to the UNIX socket created by a `greetd`-compatible program, like [greetd](https://git.sr.ht/~kennylevinsen/greetd) or [fakegreet](https://git.sr.ht/~kennylevinsen/greetd/tree/master/item/fakegreet) (a program provided by `greetd` to simulate `greetd`'s IPC) during development, for instance to `/run/greetd.sock`.

**Comment by apognu** [comment]
As for your specific request to add global padding to the terminal area, I will try and implement it.

**Comment by apognu** [comment]
I added the `--window-padding` to `master`. I will test it out for a while on there before it can be published in a stable release.

Please add comment and reopen if you feel something is wrong.

**Comment by rYR79435** [comment]
Thank you so much.
I gave it a quick test as well and everything seems to work as expected. Fantastic.
