### ISSUE TITLE
Remember Previous Session

### ISSUE THREAD

**Issue by ibrokemypie** [apognu/tuigreet#30]
Currently using tuigreet as a display manager you must select your session every log in, it would be very convenient to have it remember the last used session and start it like other display managers

**Comment by apognu** [comment]
2be3b60 should do what you want. Coud you confirm?

I guarded this behavior behind the `--remember-session` option, since I am not sure this is something that should be default (it overrides the explicitely-given `--cmd` after all).

**Comment by ibrokemypie** [comment]
Yep, that works great, thankyou!
