### ISSUE TITLE
[Feature request] Multihead support

### ISSUE THREAD

**Issue by fabien-michel** [apognu/tuigreet#31]
No idea how it could be done, maybe impossible since tuigreet use a tty.

On a laptop, when an external monitor is connected, nothing is show on it. 
It would be great to have an option to display mirrored tuigreet on all available screens.

**Comment by apognu** [comment]
I'm not sure how much this is related to tuigreet as opposed to your console settings. On my system and those of people around me, tuigreet is mirrored on all connected screens.

We do not have any notion of screens.

Do your `tty`s shells show on all screens?

**Comment by fabien-michel** [comment]
Ok you aure true. My external monitor stay black for many seconds
