### ISSUE TITLE
How can I change the font size of tuigreet?

### ISSUE THREAD

**Issue by Zeioth** [apognu/tuigreet#35]
I've tried `GRUB_GFXMODE=800x600`. And by editting `/etc/greetd/styles.css`. But neither of them seem to have effect over tuigreet.

**Comment by Zeioth** [comment]
Ok found it:

You have to run
`sudo vim /etc/vconsole`

Now just use the font you like. For example:

```
# requires sudo pacman -S terminus-font
FONT=ter-132n
```

**Comment by jcbevns** [comment]
Those looking for nixos config you'll find the same option in your `configuration.nix`

```nix
  i18n.defaultLocale = "en_US.UTF-8";
   console = {
   font = "Lat2-Terminus22";    # Terminus size 22
   ...
   };
```
