### ISSUE TITLE
High CPU consumption since 0.7.0

### ISSUE THREAD

**Issue by varqox** [apognu/tuigreet#44]
In 0.7.0, 0.7.1 and master (64a41c33999b37b06e8799810b742b12ec4a30ad), the CPU consumption is unreasonably high -- htop shows that tuigreet uses around 160% CPU.
When I tried 0.6.1 it came down to around 0% and this is reasonable. When I inspected with strace what was happening at 0.7.1, a lot of futex() calls appeared, so it looks like a lot of busy waiting (I saw that in between 0.6.1 and 0.7.0 some code was moved to async).

greetd command = tuigreet -c zsh
System: Arch Linux

**Comment by bezirg** [comment]
I can confirm as well about the high cpu usage.

**Comment by DjLogozzo** [comment]
I can confirm to also having high cpu usage in 0.7.0 and later,
Using `git bisect`, it seems the commit that introduced the issue was f12688fa0d34a2063a086f84b6144d6dbaac7f8f

**Comment by DjLogozzo** [comment]
After a bit of testing, this loop continuously obtaining a write lock on the greeter does seem to be the issue, a simple (if a bit crude) solution to this would be to add a small async sleep to the loop so it isn't just free-running constantly. Here is an example of this solution committed to my fork https://github.com/DjLogozzo/tuigreet/blob/8c1044dec4e2d05cc69bac20ce4651eed19568e9/src/main.rs#L71-L85

**Comment by DjLogozzo** [comment]
After thinking about it for a bit, a fairly unobtrusive but more complete solution (compared to a simple async sleep, however it's still a band-aid solution) would be to use a tokio [Notify](https://docs.rs/tokio/1.14.0/tokio/sync/struct.Notify.html) system, and parking the thread until the `power_command` gets updated by the user, I've implemented a fix using this solution  to my fork https://github.com/DjLogozzo/tuigreet/commit/8c1044dec4e2d05cc69bac20ce4651eed19568e9 (Which has updated the accompanying PR #46).

**Comment by apognu** [comment]
Sorry I haven't been available those past few months, it's been a bit hectic on my side. I'll look at the PR and come back to you.

**Comment by apognu** [comment]
[0.7.2](https://github.com/apognu/tuigreet/releases/tag/0.7.2), which includes this fix, was tagged and deployed.
