### ISSUE TITLE
showing further console output

### ISSUE THREAD

**Issue by aserowy** [apognu/tuigreet#45]
Heho,

im running tuigreet with nixos. After greetd triggers some services are initialized. The output is rendered over tuigreet.

![IMG20211103070952](https://user-images.githubusercontent.com/8199164/140019761-0660069f-ea8f-45dc-8ae9-928698740fcb.jpg)

My tuigreet config is

<https://github.com/aserowy/nixos/blob/main/shell/sway/tuigreeter.nix>

Sorry in advance if im stupid :D

Kind regards
Alexander

**Comment by jonseitz** [comment]
I think this is a duplicate of #17, and there are a couple of nixos-specific solutions in that thread.

**Comment by aserowy** [comment]
thanks for the heads up.
