### ISSUE TITLE
F12 does not show power options

### ISSUE THREAD

**Issue by xeruf** [apognu/tuigreet#48]
On a fresh [manjaro-sway](https://github.com/Manjaro-Sway/manjaro-sway) installation. I can only force-reboot with `ctrl-alt-backspace`.
Am I doing something wrong? Is something misconfigured?

**Comment by DjLogozzo** [comment]
According to the [manjaro-sway iso.pkg](https://github.com/Manjaro-Sway/manjaro-sway/releases/download/202112070241/manjaro-sway-21.1.0-211207-linux515.iso.pkgs) file, manjaro-sway comes packaged with tuigreet [v0.2.0](https://github.com/apognu/tuigreet/releases/tag/0.2.0), power options were not added until [v0.4.0](https://github.com/apognu/tuigreet/releases/tag/0.4.0) with commit c2a0ba75ab40f26e2910619dc6e4349b238694c5.

You should be able to update tuigreet to the latest version as its in the AUR [v0.7.1-1](https://aur.archlinux.org/packages/greetd-tuigreet/), which should allow you to use the power options.

**Comment by Mathew-D** [comment]
I am running the current version from manjaro and when I run `tuigreet -v`, I get:
`tuigreet 0.7.1 (x86_64-unknown-linux-gnu)`

So when you update manjaro it will update to 0.7.1

**Comment by apognu** [comment]
If I understand correctly, this issue was with the repository maintainers, I'll close this.
