### ISSUE TITLE
--time Date time format specification

### ISSUE THREAD

**Issue by funcrab** [apognu/tuigreet#49]
Thank you for making this useful tool.

I'm using a Japanese locale, and the kanji characters in the date/time part are garbled and cannot be displayed in the font on agetty. 
![image](https://user-images.githubusercontent.com/55499652/145694164-af169086-1fd2-4fb5-aced-8c4a827ade24.png)
For example, it would be helpful if the --time argument could be used to specify the display format in the format of the date command.

Thank you for your consideration.

**Comment by funcrab** [comment]
After adding the following settings, I was able to set the display to English.
```
# cat /root/.config/locale.conf
LC_MESSAGES="en_US.UTF-8"
#
```
![image](https://user-images.githubusercontent.com/55499652/145695346-5b47d41d-738c-4038-9077-384e970421bc.png)

If this is very easy to implement,  consider it.
If not, or if it doesn't interest you, feel free to close it.

Thanks for your work.

**Comment by DjLogozzo** [comment]
You can localise this program to your native locale by creating a locale file.
PR #36 and #37 contain examples of this.

**Comment by funcrab** [comment]
I am thinking that due to agetty's limitation (only 256 or 512 character representation fonts can be used), unicode fonts cannot be displayed as Japanese, and tuigreet cannot display Japanese either. Is that correct?

https://wiki.archlinux.org/title/Linux_console#Fonts

> Note: This section is about the Linux console. For alternative console solutions offering more features (full Unicode fonts, modern graphics adapters etc.), see KMSCON or similar projects.

If so, do you think it is possible to use tuigreet with other consoles, such as KMSCON or fbterm?
As far as I have run it lightly, I have not been able to get tuigreet to show up within KMSCON.

**Comment by funcrab** [comment]
I don't think there's any problem, so I'll close it.
