### ISSUE TITLE
Remember last session per user

### ISSUE THREAD

**Issue by VannTen** [apognu/tuigreet#50]
Hi,

I was wondering if you would consider a pull request adding support for a cached
last session, but per user ?
The idea being that when there is several people using a computer, usually each
one will use the same session most of the time.

I'm thinking this could be done like the last session support, with something
like `/var/cache/tuigreet/<user>/lastsession`; when the user is chosen, this
file is checked for existence the same way that for lastsession, and the cmd
adjusted accordingly.

What do you think ?

I'm willing to add that myself (that will make a good rust first experiment) if
needed, but do you think it's in the scope of tuigreet ?

Thanks for your work.

**Comment by apognu** [comment]
I actually thought of something like this and the beginning of a patch written to handle this. I had to go on a hiatus those past few months but will think about it 

Feature-wise, it makes sense.
