### ISSUE TITLE
Show users custom launch command under "Choose session" (or equivalent)

### ISSUE THREAD

**Issue by Nuc1eoN** [apognu/tuigreet#52]
So I have my own launch command configured:
```toml
command = "tuigreet --cmd wayfire-launch.sh"
```

And tuigreet shows it nicely as default at the bottom, displaying "CMD wayfire-launch.sh".

However the launch command does not appear in the list when pressing F3. So that means once I choose a different session from that menu, I will "lose" my default command in that situation.

Ok good, personally I can remember it, so I can type it in again as a custom command with F2.

But I think it should not just disappear and be inaccessable afterwards. 

Why not put it under the "Choose session" (F3) commands :)

**Comment by apognu** [comment]
This makes sense, I'll implement this.

**Comment by apognu** [comment]
This is done on `master` (so is testable by manually compiling) and will be included in `0.8.0`.
