### ISSUE TITLE
Random init log messages sliding into tuigreet

### ISSUE THREAD

**Issue by Nuc1eoN** [apognu/tuigreet#53]
Today I had a "random" systemd log message slide into tuigreet:
![Untitled](https://user-images.githubusercontent.com/2538022/151095114-52099333-908b-4508-a864-b7c7bbb10a58.jpeg)
```
[ OK ] Finished Daily man-db regeneration
```
As you see the input field is also garbled sadly (where it should say "Username:"

In this case it is not severe, however maybe if possible it should be prevented somehow?

I have never seen the "default tty login screen" ever having random init log messages appear, for what it's worth.

**Comment by mredaelli** [comment]
I just installed `tuigreet`, and the same thing happens to me, though a bit more violently :)

I use NixOS, and copy-pasted the snippet in the README

**Comment by mredaelli** [comment]
Ah wait https://github.com/apognu/tuigreet/issues/17

**Comment by Nuc1eoN** [comment]
Oh ok ok shit... seems like it cannot really be fixed then.

I have a question though, why doesn't the "standard tty login form" get overriden by startup logs?
Is it somehow immune to this, in a way that tuigreet isn't?

**Comment by apognu** [comment]
Well, at least this ticket has shown an issue with my handling of the power commands, I was supposed to suppress the outputs, but did not in the default case.

I will push a fix to correctly suppress the output and start thinking about a way to display any error shown on `stderr`.

**Comment by Nuc1eoN** [comment]
@apognu Would you mind to explain what you have changed in the current behavior? It is marked as `wontfix`but there seem to have been some changes commited :)

**Comment by apognu** [comment]
That is my bad, really, I wrote the wrong issue number, that is related (but does not fix) the issue related to the power commands output.

This problem with systemd/kernel messages showing on top of `tuigreet` has already been mentioned several times, and I really have no idea if I can do anything about it. I don't see how to prevent the kernel or a root process from writing to `/dev/ttyX` from my side.

If anyone has an idea, I would be happy to research it, but until then, this will remain as `wontfix`.
