### ISSUE TITLE
unusable on gentoo here...

### ISSUE THREAD

**Issue by CaptainBloodz** [apognu/tuigreet#57]
```
CHECKVT=1
DISPLAYMANAGER="greetd"
--------------------------------------
running openrc+elogind here.
----------------------
[I] gui-libs/greetd
     Installed versions:  0.8.0(12:07:21 02/12/2021)(man -debug)
CFLAGS="-march=skylake -O1-pipe -Wa,-mbranches-within-32B-boundaries"
CXXFLAGS="-march=skylake -O1-pipe -Wa,-mbranches-within-32B-boundaries"
LDFLAGS="-Wl,-O1 -Wl,-fuse-ld=bfd -march=skylake -O1-pipe -Wa,-mbranches-within-32B-boundaries"
--------------------------
[I] gui-apps/tuigreet
     Installed versions:  0.7.2(21:38:18 23/02/2022)(-debug)
USE="-debug" ABI_X86="(64)"
CFLAGS="-march=skylake -O1-pipe -Wa,-mbranches-within-32B-boundaries"
CXXFLAGS="-march=skylake -O1-pipe -Wa,-mbranches-within-32B-boundaries"
```
----------------------------------------------------------------------------
login & password keystroke not always echoed on screen
choose session get stuck while Arrow-Up Arrow-Down
text input cursor finally jumps to the left side of the screen.

Things are running so bad here, I must be doing the wrong way as a whole.
No idea what to change...

**Comment by apognu** [comment]
That's quite interesting. If this is confirmed, I will add a note to the README.

**Comment by CaptainBloodz** [comment]
Cancelling
c1:12345:respawn:/sbin/agetty 38400 tty1 linux --noclear
in /etc/inittab
didn't change anything here.
