### ISSUE TITLE
Set terminal colors

### ISSUE THREAD

**Issue by rogueai** [apognu/tuigreet#59]
Hi,
I'm trying to achieve what's shown in the screenshot in the README, basically I'd like to be able to change the color scheme of the login screen.

I've tried setting escape codes in my .bashrc for the "linux" term, but that only seems to affect the tty after login.

I understand this is probably a general question not strictly related to your project, but would you mind sharing how you were able to achieve that?

Thanks!

**Comment by rogueai** [comment]
Ok so I've done some more researching and found out vt colors can actually be set as kernel parameters, using `setvtrgb`

On Arch, a simple mkinitcpio hook can be added to take care of setting the colors back on upgrades, there's a project doing exactly that:
https://github.com/coderonline/base16-vtrgb

I'm going to close the issue and leave this here for future reference. Thanks!

**Comment by Jarvvski** [comment]
For anyone else coming here, but not on Arch (like ubuntu / debian), check out this [great blog](https://www.chucknemeth.com/linux/ricing/virtual_terminal_color) post that explains how to use an `initramfs` hook. Similar to `mkinitcpio` as in Arch

**Comment by stevensonmt** [comment]
See also https://github.com/evanpurkhiser/mkinitcpio-colors

**Comment by erdnuesse** [comment]
Any hints on using it with dracut?

**Comment by Kabouik** [comment]
For any one using Guix, there is no need to use `kbd`, `initramfs` and download themes, colors can just be set declaratively in `config.scm` with:

```scm
  (kernel-arguments
   (cons* "vt.default_red=0x3b,0xbf,0xa3,0xeb,0x81,0xb4,0x88,0xe5,0x4c,0xbf,0xa3,0xeb,0x81,0xb4,0x8f,0xec" ;; Nord colors in tty
          "vt.default_grn=0x3b,0x61,0xbe,0xcb,0xa1,0x88,0xc0,0xe5,0x56,0x61,0xbe,0xcb,0xa1,0x88,0xbc,0xef"
          "vt.default_blu=0x3b,0x61,0x8c,0x8b,0xc1,0xe8,0xd3,0xe5,0x66,0x61,0x8c,0x8b,0xc1,0xe8,0xbb,0xf4"
          %default-kernel-arguments))
```
