### ISSUE TITLE
binaries vary across builds

### ISSUE THREAD

**Issue by bmwiedemann** [apognu/tuigreet#60]
While working on [reproducible builds](https://reproducible-builds.org/) for [openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds), I found that our [`tuigreet-0.7.1` package](https://github.com/bmwiedemann/openSUSE/blob/master/packages/t/tuigreet/tuigreet.spec) varied across builds.

The variations stop when readdir order is not random.

```diff
--- old /usr/bin/tuigreet (objdump)
+++ new /usr/bin/tuigreet (objdump)
@@ -255,14 +255,14 @@
  21efa0 40000000 00000000 60000000 00000000  @.......`.......
  21efb0 01000000 00000000 02000000 00000000  ................
  21efc0 05000000 00000000 04000000 00000000  ................
- 21efd0 706c2d50 4c2f7475 69677265 65742e66  pl-PL/tuigreet.f
+ 21efd0 70742d42 522f7475 69677265 65742e66  pt-BR/tuigreet.f
  21efe0 746c0000 00000000 00000000 00000000  tl..............
  21eff0 63612d45 532f7475 69677265 65742e66  ca-ES/tuigreet.f
- 21f000 656e2d55 532f7475 69677265 65742e66  en-US/tuigreet.f
- 21f010 69742d49 542f7475 69677265 65742e66  it-IT/tuigreet.f
- 21f020 64652d44 452f7475 69677265 65742e66  de-DE/tuigreet.f
- 21f030 70742d42 522f7475 69677265 65742e66  pt-BR/tuigreet.f
- 21f040 66722d46 522f7475 69677265 65742e66  fr-FR/tuigreet.f
+ 21f000 66722d46 522f7475 69677265 65742e66  fr-FR/tuigreet.f
+ 21f010 706c2d50 4c2f7475 69677265 65742e66  pl-PL/tuigreet.f
+ 21f020 69742d49 542f7475 69677265 65742e66  it-IT/tuigreet.f
+ 21f030 64652d44 452f7475 69677265 65742e66  de-DE/tuigreet.f
+ 21f040 656e2d55 532f7475 69677265 65742e66  en-US/tuigreet.f
```

suggests, this comes from how `contrib/locales/` is used without sorting the entries.
Can you help me find the right place to fix this?

**Comment by apognu** [comment]
I don't have a lot of free time these days to look into it, but locale files and loaded and embedded by through the `rust-embed` crate, which if I remember correctly doesn't do any kind of sorting of the files in the included directory.

I'll open an issue there when I can to see if they can help.

I'll also try and reproduce the issue if I can. Did you have to do something in particular to see the different outputs? Or does it happen all the time?

**Comment by bmwiedemann** [comment]
Issues from filesystem readdir order can be a bit tricky to reproduce as building twice on the same filesystem will still give identical results.

One way to reproduce can be a `disorderfs` fuse mount and another way can be to use mkfs.ext4 (defaults to enabled dirindex) to build on new scratch filesystems.

**Comment by bmwiedemann** [comment]
I don't see an issue at https://github.com/pyros2097/rust-embed/issues - do you still plan to open one or is it in another place?

**Comment by apognu** [comment]
I just created the issue upstream and will try and watch responses there. I offered to prepare a PR if necesary.

**Comment by apognu** [comment]
@bmwiedemann My PR in `rust-embed` was merged, waiting for the next release to use it here.

**Comment by bmwiedemann** [comment]
https://github.com/pyros2097/rust-embed/pull/173/commits/5574de9c39b988573e88145c6235e8ab3ff4eab7 looks simple enough. Thanks for this.

**Comment by apognu** [comment]
I updated `tuigreet`'s dependencies with the updated upstream `rust-embed`, can you confirm if the issue is gone?

**Comment by bmwiedemann** [comment]
I finally managed to test the 1-line change in rust-embed-utils and it made tuigreet reproducible.

**Comment by apognu** [comment]
The bump is scheduled for the next release of `tuigreet`. I'm pretty busy nowadays, so I can't promise a date, but I'll try to make that sooner rather than later.

**Comment by denisok** [comment]
0.8.0 is there: https://build.opensuse.org/request/show/1036285
@bmwiedemann could you please check if that is fixed ?

**Comment by bmwiedemann** [comment]
Looks good now. Thanks.
