### ISSUE TITLE
kmscon

### ISSUE THREAD

**Issue by Zeioth** [apognu/tuigreet#62]
I opened [this ticket](https://todo.sr.ht/~zeioth/kmscon-support) upstream in greetd.

It would be a very desireable to have greetd/tuigreet working with kmscon. Specifically to be able to use HiDPI fonts, which tty doesn't support.

You are welcome to participate in said ticket to show support in case you consider it something positive.

**Comment by apognu** [comment]
That would make sense.

I don't know what changes, if any, would be required in `tuigreet` if this were implemented on `greetd`. I never used `kmscon` myself, so am nlmot familiar with it. In the meantime, I will try and check if the tui library I use is compatible (it is supposed to be drop-in replacement, so my guess would be it is).

Tagging as a question for now until we get news from `greetd`.

**Comment by apognu** [comment]
Without any news from `greetd`'s support for KMSCON and not using it myself, I'll close this.
