### ISSUE TITLE
`ESC` breaks layout

### ISSUE THREAD

**Issue by ykis-0-0** [apognu/tuigreet#63]
When I press the ESC key on the main page, a stray error appears in place of the prompt.

https://user-images.githubusercontent.com/64165725/162564067-38e7bade-532f-4235-ac43-9c8368881fee.mp4

**Comment by apognu** [comment]
This should not happen anymore (I believe it was because of a bad handling on my part of the IPC with `greetd`.

I know it has been two years (my bad), but do you still encounter this?

**Comment by apognu** [comment]
Closing until more information comes up.
