### ISSUE TITLE
Unable to start greetd in Debian

### ISSUE THREAD

**Issue by vuongtuha** [apognu/tuigreet#66]
I finished cargo installation and there's a big folder ~/tuigreet (around 500Mb)
Btw when I run tuigreet execution file, I got this error 
GREETD_SOCK must be defined

There's no guide for any typical distro like Debian/Fedora. Please give me struction. Tysm!

**Comment by apognu** [comment]
This is to be used in conjunction with `greetd`, it cannot be launched on its own. Actually, `greetd` will run `tuigreet`.

Installing, configuring and running `greetd` is out of scope from this repo, I think you should refer to its documentation or its page on Arch's wiki (there shouldn't be a lot of difference with Debian).
