### ISSUE TITLE
AUR update

### ISSUE THREAD

**Issue by joeftiger** [apognu/tuigreet#67]
Hello

I saw that you're the maintainer on the AUR as well:
- [greetd-tuigreet](https://aur.archlinux.org/packages/greetd-tuigreet)
- [greetd-tuigreet-bin](https://aur.archlinux.org/packages/greetd-tuigreet-bin)
- [greetd-tuigreet-git](https://aur.archlinux.org/packages/greetd-tuigreet-git)

Is it possible for you to update it there as well?
The release of `0.8.0` has been 28 days ago :-)
I've manually updated some days ago.

Thank you!

**Comment by apognu** [comment]
Hi, sorry about the delay, it should have been updated yesterday.
