### ISSUE TITLE
greet exits without any error on openSUSE

### ISSUE THREAD

**Issue by denisok** [apognu/tuigreet#7]
Hi,

I have packaged tuigreet for openSUSE:
https://build.opensuse.org/package/show/home:dkondratenko/tuigreet

all other greeters (gtk, wl) are working good, but tui doesn't work. When I am trying enter my login cursor jums backwards and after some tries greeter just exits.
I don't see anything useful in the logs:
`greetd[1195]: error: check_children: greeter exited without creating a session`

How to debug the issue? Any debug flags or something ?

**Comment by denisok** [comment]
I fixed some static dirs, and some other stuff, and can't reproduce this on fresh VM install

**Comment by apognu** [comment]
Do you have an idea of which directory caused the issue? That may help me implement a saner behavior in thoses cases.

**Comment by denisok** [comment]
https://build.opensuse.org/package/rdiff/X11:Wayland/greetd?linkrev=base&rev=3

maybe /var/lib/... where greeter user should point to... and cache as we..// but I am not sure... that the only change I did and actually I didn't try it on clean VM before that, maybe my system is messed up...
