### ISSUE TITLE
Bottom Left Bar Given too little space

### ISSUE THREAD

**Issue by wisnoskij** [apognu/tuigreet#70]
On low-ish resolutions the end of CMD is cut off as the bottom left bar seem to be given exactly half the screen.

This seems to be completely unnecessary as the only thing occupying the right side is "CAPS LOCK".

Expected behaviours:
Bottom of the screen to read:
"... F12 Power CMD /bin/bash"

What actually happens:
"... F12 CMD /bin"

**Comment by apognu** [comment]
That is interesting. And since we know the max size of the right part, I should be able to expand the left section as far as possible.

**Comment by apognu** [comment]
On `master`, the status bar should now be mostly available to the left part, with only the required space for caps lock indicator left to the right part.
