### ISSUE TITLE
Feature request: Support for symlinks

### ISSUE THREAD

**Issue by UtkarshVerma** [apognu/tuigreet#73]
I like to maintain my dotfiles using stow, which means my configs usually end up being symlinks to another directory. For sessions, I have made a directory `/etc/tuigreet/sessions` which I pass through the `--sessions` flag. That directory is symlinked to my dotfiles folder.

`tuigreet` currently doesn't resolve symlinks due to which I can't see those sessions in the login screen. Therefore, it would be really great to have support for this.

**Comment by apognu** [comment]
Closing unless more information comes up.

**Comment by UtkarshVerma** [comment]
I took a look at this today and it was a permissions issue indeed. Using `chmod o+x <dir>` for all parents of the tugreet sessions fixed it.
