### ISSUE TITLE
Menu gets stuck if two submenus opened

### ISSUE THREAD

**Issue by eddsalkield** [apognu/tuigreet#8]
If a user presses F2 to change command, and then immediately F3 to choose session, or vice versa, then exits the top-level menu, the underlying menu is stuck open.  The user cannot log in, and the program becomes unresponsive.

I'm experiencing this issue in `tuigreet` 0.2.0, on Fedora 32.

**Comment by IchikaOmamori** [comment]
> If a user presses F2 to change command, and then immediately F3 to choose session, or vice versa, then exits the top-level menu, the underlying menu is stuck open.  The user cannot log in, and the program becomes unresponsive.
> 
> 
> 
> I'm experiencing this issue in `tuigreet` 0.2.0, on Fedora 32.

Still happened
