### ISSUE TITLE
Version misreported in 0.8.0

### ISSUE THREAD

**Issue by dsh0005** [apognu/tuigreet#84]
Version 0.8.0-r1 on Gentoo reports it's version as 0.7.3:
```
$ equery l tuigreet
 * Searching for tuigreet ...
[IP-] [  ] gui-apps/tuigreet-0.8.0-r1:0
$ tuigreet --version
tuigreet 0.7.3 (x86_64-unknown-linux-gnu)
Copyright (C) 2020 Antoine POPINEAU <https://github.com/apognu/tuigreet>.
Licensed under GPLv3+ (GNU GPL version 3 or later).

This is free software, you are welcome to redistribute it under some conditions.
There is NO WARRANTY, to the extent provided by law.
```

It looks like it's getting that from your Cargo.toml, although I can't find documentation mentioning `VERSION` instead of `CARGO_PKG_VERSION`.
https://github.com/apognu/tuigreet/blob/c955066af94078b0503f764e6f5f591e7943ee11/src/greeter.rs#L398
https://github.com/apognu/tuigreet/blob/c955066af94078b0503f764e6f5f591e7943ee11/Cargo.toml#L3

**Comment by apognu** [comment]
Good catch, it will be fixed in the next version.
