### ISSUE TITLE
Fedora SELinux

### ISSUE THREAD

**Issue by scabala** [apognu/tuigreet#85]
Hi,
it's great project, using it daily.

I had problems with `--remember` options running on Fedora with SELinux in enforcing mode. Here's what I did to make it work.
Assuming that `tuigreet` is installed in `/usr/local/bin`:

```bash
sudo mkdir -p /var/cache/tuigreet
sudo chown greetd:greetd -R /var/cache/tuigreet

sudo semanage fcontext -a -t xdm_exec_t '/usr/local/bin/tuigreet'
sudo restorecon /usr/local/bin/tuigreet

sudo semenage fcontext -a -t xdm_var_lib_t '/var/cache/tuigreet(/.*)?'
sudo restorecon -R /var/cache/tuigreet
```

Hope it helps anybody. It should be useful if anyone wants to create RPM package for Fedora, too.

**Comment by alebastr** [comment]
> ```
> sudo semanage fcontext -a -t xdm_exec_t '/usr/local/bin/tuigreet'
> sudo restorecon /usr/local/bin/tuigreet
> ```

This should not be necessary, `tuigreet` inherits the context from `greetd`.

**Comment by scabala** [comment]
You're right, I undo it it still worked fine.

**Comment by apognu** [comment]
I assume this is not an issue anymore (and overall was not an issue with `tuigreet` itself)?
