### ISSUE TITLE
[Bug]: tuigreet cannot be started on the VM

### ISSUE THREAD

**Issue by QingyaoLin** [apognu/tuigreet#88]
I want to use tuigreet to start startx and then enter bspwm.

system: Nixos
Minimum configuration:
```nix
# login manager
services.greetd = {
  enable = true;
  package = pkgs.greetd.tuigreet;
  settings = rec {
    default_session = {
      command = "${pkgs.greetd.tuigreet}/bin/tuigreet --time --cmd startx";
      user = "greeter";
    };
  };
};

environment.variables = {
  RUST_BACKTRACE = "1";
};
```

error output:
![tuigreet_error](https://user-images.githubusercontent.com/83944508/218231260-fc242039-a013-41f3-84d5-26111a693d34.png)

I tried to adjust the screen scale of the virtual machine, but failed.

**Comment by IchikaZou** [comment]
This is not just happen in VM, I have the same situation when I update to kernel 6.x.

when I downgrade to 5.19.x everything work fine.

**Comment by apognu** [comment]
This should be fixed on `master`. The size calculations were buggy on small sizes.
