### ISSUE TITLE
npm run start permission denied

### ISSUE THREAD

**Issue by jake883j** [apognu/tuigreet#90]
when I run npm run start in my MacBook terminal I get this: 
<img width="682" alt="Screenshot 2023-03-21 at 4 27 21 PM" src="https://user-images.githubusercontent.com/128553728/226764310-6683cb21-5149-45ef-8ca9-26e28c847aa0.png">

I've already made it so that I have read and write permissions

**Comment by apognu** [comment]
I believe you created this on the wrong repository. Closing.
