### ISSUE TITLE
fprint support

### ISSUE THREAD

**Issue by lcnbr** [apognu/tuigreet#99]
Is there a way to sign in with fprint?

**Comment by apognu** [comment]
`greetd` uses your PAM configuration to provide prompts to the greeter, so my initial throught would be that, with a properly-configured PAM setup, it would work out of the box.

Isn't it the case?

**Comment by apognu** [comment]
I'll close this because controlling authentication workflow is outside of this project's scope and should be configured in PAM.

You can open an issue if you feel `tuigreet` does not work well with it, though.
